POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVlcm9qYWxhIiwiaWQiOiI2MDA5NjE1NzE5YjkxMzQyN2MzYmM5NGUiLCJpYXQiOjE2MTEyNDQwMDJ9.q_-Ut-fJlta1AepKtE8YwkCPfyfBDlN8rgZ15Zcaldo

{
    "title": "Hello world 3", "author": "Eero Ojala", "url": "http://localhost:3001/api/blogs", "likes": 12
}